version: '3.8'
services: 
  # Conference API service
  # conferenceapi:
  #   build:
  #     context: ./ConferenceApi
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development

  # Payment API service
  # paymentapi:
  #   build:
  #     context: ./Payment.Api
  #   ports:
  #     - "5001:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development

  # # Register API service
  # registerapi:
  #   build:
  #     context: ./RegisterApi
  #   ports:
  #     - "5002:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  # apigateway:
  #   image: apigateway
  #   ports:
  #       - "5003:80"
  #   environment:
  #       - ASPNETCORE_ENVIRONMENT=Development
  #   depends_on:
  #     - conferenceapi
  #     - paymentapi
    
  mongo: 
    image: mongo
    container_name: mongo
    ports: 
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  rabbitMq:
    image: rabbitmq:management   
    container_name: rabbitMq
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq   
volumes:
  mongodbdata:
  rabbitmqdata: