namespace Payment.Api.Models;

public class StripeProduct
{
    public string? Id { get; set; } // Optional, can be generated by Stripe
    public string? Name { get; set; }
    public string? Description { get; set; }
    public string? Category { get; set; }
    public long Price { get; set; }
    public string? Type { get; set; }
    public bool IsRecurring { get; set; }
    public bool Active { get; set; }
}
